version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mariabuntovskikh/chat_be
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_ENGINE: django.db.backends.postgresql
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mariabuntovskikh/chat_fe
    ports:
      - "5173:5173"
    environment:
      ORIGIN: http://localhost:5173
      PUBLIC_API_URL: http://backend:8000
      PUBLIC_WS_URL: ws://localhost:8000/ws/chat
      PUBLIC_WS_GLOBAL_URL: ws://localhost:8000/ws/global

volumes:
  postgres_data:
